module.exports = {
  texts:[
    {
      "HIDDEN":"VBPUGKQNDKVFVBSNGXFHVWFAPNUAWVYVPCLMQHRFGQHVBQXGTGSPCPVPVRBUUAYVPFYVBLEBKFCNWASUBVCN",
      "KEY":"VELUDO"
    },
    {
      "HIDDEN":"CWUFGKQNRKCPCWFZPDRGDUHWONFDUDURALIPXPOFGPKBTHDPOPASLABQAQHCFDURNRURTWTLHFSLQDTFWCSL",
      "KEY":"ALTURA"
    }
  ]
}
